package io.github.zhengfangfang0304.synspt.motion;

import io.github.zhengfangfang0304.synspt.motion.parameters.AttmParameters;
import io.github.zhengfangfang0304.synspt.motion.parameters.BrownianParameters;
import io.github.zhengfangfang0304.synspt.motion.parameters.ConfinedParameters;
import io.github.zhengfangfang0304.synspt.motion.parameters.CtrwParameters;
import io.github.zhengfangfang0304.synspt.motion.parameters.DirectedParameters;
import io.github.zhengfangfang0304.synspt.motion.parameters.FbmParameters;
import io.github.zhengfangfang0304.synspt.motion.parameters.LevyWalkParameters;
import io.github.zhengfangfang0304.synspt.motion.parameters.MotionParameters;
import io.github.zhengfangfang0304.synspt.motion.parameters.SbmParameters;

/** Creates a strongly typed motion implementation from immutable parameters. */
public final class MotionModelFactory {

    private MotionModelFactory() {
    }

    public static MotionModel create(MotionParameters parameters) {
        if (parameters == null) {
            throw new IllegalArgumentException("Motion parameters cannot be null.");
        }

        switch (parameters.getMotionType()) {
            case BROWNIAN:
                return new BrownianMotion(requireType(parameters, BrownianParameters.class));
            case DIRECTED:
                return new DirectedMotion(requireType(parameters, DirectedParameters.class));
            case CONFINED:
                return new ConfinedDiffusion(requireType(parameters, ConfinedParameters.class));
            case FBM:
                return new FBM(requireType(parameters, FbmParameters.class));
            case CTRW:
                return new CTRW(requireType(parameters, CtrwParameters.class));
            case LEVY_WALK:
                return new LevyWalk(requireType(parameters, LevyWalkParameters.class));
            case SBM:
                return new SBM(requireType(parameters, SbmParameters.class));
            case ATTM:
                return new ATTM(requireType(parameters, AttmParameters.class));
            case MULTI_STATE:
                throw new IllegalArgumentException(
                        "Multi-state motion must be generated by MultiStateMotion."
                );
            default:
                throw new IllegalArgumentException(
                        "Unsupported motion type: " + parameters.getMotionType()
                );
        }
    }

    private static <T extends MotionParameters> T requireType(
            MotionParameters parameters,
            Class<T> expectedType
    ) {
        if (!expectedType.isInstance(parameters)) {
            throw new IllegalArgumentException(
                    "Motion type " + parameters.getMotionType()
                            + " requires " + expectedType.getSimpleName() + "."
            );
        }
        return expectedType.cast(parameters);
    }
}
